<a href="https://colab.research.google.com/github/ShreyansGupta/Minesweeper/blob/master/MineSweeper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import random

In [0]:
#random.seed(1)
class Environment:
  def __init__(self, d, n):
    '''
    d -> int : Dimension of board
    n -> int : Number of mines
    '''
    self.dimension = d
    self.no_of_mines = n
    self.mazeCells = np.array([0]*((d*d)-n) + [-1]*(n))
    np.random.shuffle(self.mazeCells)
    self.mazeCells = np.reshape(self.mazeCells,(d,d))
    
    
  def reveal(self,row,column):
      if self.mazeCells[row][column] == -1 :
          return -1;  
      count = 0
      if row >= 1:
        if column>=1 and self.mazeCells[row-1][column-1] == -1:
          count +=1
        if column<self.dimension-1 and self.mazeCells[row-1][column+1] == -1:
          count +=1
        if self.mazeCells[row-1][column] == -1:
          count +=1

      if column >= 1:
        if row<self.dimension-1 and self.mazeCells[row+1][column-1] == -1:
          count +=1
        if self.mazeCells[row][column-1] == -1:
          count +=1

      if row < self.dimension-1:
        if column<self.dimension-1 and self.mazeCells[row+1][column+1] == -1:
          count +=1
        if self.mazeCells[row+1][column] == -1:
          count +=1

      if column < self.dimension-1 and self.mazeCells[row][column+1] == -1:
        count +=1
      return count

In [0]:
maze = Environment(20,80)
print(maze.mazeCells)    

[[ 0  0  0  0 -1 -1  0 -1  0 -1 -1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 -1 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 -1  0  0  0  0  0]
 [-1  0  0  0  0  0 -1  0  0  0 -1 -1  0 -1  0  0  0  0  0  0]
 [-1  0  0 -1  0  0  0  0  0  0  0  0  0  0 -1  0  0  0  0 -1]
 [-1  0  0  0  0  0  0  0 -1  0  0  0 -1  0  0  0 -1  0  0  0]
 [ 0  0  0  0  0  0  0 -1  0 -1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 -1 -1  0  0  0  0  0 -1  0  0  0  0  0]
 [ 0  0 -1 -1  0  0  0 -1  0  0  0  0 -1  0  0 -1 -1  0  0  0]
 [ 0  0 -1  0  0  0 -1  0  0 -1  0  0  0  0  0  0  0 -1  0  0]
 [-1 -1  0  0 -1  0  0 -1  0  0 -1  0  0 -1 -1  0 -1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 -1 -1  0  0]
 [ 0  0  0  0  0  0 -1  0  0  0 -1  0  0 -1  0  0  0  0  0  0]
 [-1  0  0  0 -1  0  0  0 -1 -1 -1  0  0 -1  0  0 -1  0  0  0]
 [ 0  0  0  0  0  0  0 -1  0  0 -1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 -1  0  0  0  0 -1  0  0  0  0  0 -1

In [0]:
class Agent:
  def __init__(self,env):
    self.dimension=env.dimension
    self.env = env
    self.agentBoard = np.array([-2]*(self.dimension*self.dimension))
    self.agentBoard = np.reshape(self.agentBoard,(self.dimension,self.dimension))    

  def get_knowledge(self,row,column): 
      #Unrealved : returns list of coordinates
      #revealed = 8-len(unrevealed)  
      #count_revealed: revealed - revealed mines
      unrevealed = []
      revealed = 0
      revealed_mines = 0

      if row >= 1:  
          if column>=1:
              if self.agentBoard[row-1][column-1] == -1:
                  revealed_mines +=1
              elif self.agentBoard[row-1][column-1] == -2:
                  unrevealed.append((row-1,column-1))

          if column<self.dimension-1:
              if self.agentBoard[row-1][column+1] == -1:
                  revealed_mines +=1
              elif self.agentBoard[row-1][column+1] == -2:
                  unrevealed.append((row-1,column+1))

          if self.agentBoard[row-1][column] == -1:
              revealed_mines +=1
          elif self.agentBoard[row-1][column] == -2:
              unrevealed.append((row-1,column))

      if column >= 1:
          if row<self.dimension-1:
              if self.agentBoard[row+1][column-1] == -1:
                  revealed_mines +=1
              elif self.agentBoard[row+1][column-1] == -2:
                  unrevealed.append((row+1,column-1))

          if self.agentBoard[row][column-1] == -1:
              revealed_mines +=1
          elif self.agentBoard[row][column-1] == -2:
              unrevealed.append((row,column-1))

      if row < self.dimension-1:
          if column<self.dimension-1:
              if self.agentBoard[row+1][column+1] == -1:
                  revealed_mines +=1
              elif self.agentBoard[row+1][column+1] == -2:
                  unrevealed.append((row+1,column+1))

          if self.agentBoard[row+1][column] == -1:
              revealed_mines +=1
          elif self.agentBoard[row+1][column] == -2:    
              unrevealed.append((row+1,column))

      if column < self.dimension-1:
          if self.agentBoard[row][column+1] == -1:
              revealed_mines +=1
          elif self.agentBoard[row][column+1] == -2:
              unrevealed.append((row,column+1))


      revealed = 8-len(unrevealed)  
      safe_revealed = revealed - revealed_mines
      return (unrevealed, safe_revealed, revealed_mines)

  def updateKnowledge(self):
    noOfIter = 0
    while(self.updateKnowledgeIter() > 0):
      self.queryUnQueried()
      noOfIter += 1
    return noOfIter

  def queryUnQueried(self):
    for i in range(self.dimension):
      for j in range(self.dimension):
        if(self.agentBoard[i][j] == -3):
          self.agentBoard[i][j] = self.env.reveal(i,j)
          

  def updateKnowledgeIter(self):
      count = 0
      for i in range(self.dimension):
          for j in range(self.dimension):
              count += self.updateNeighbours(i,j)
      return count;
          

  def updateNeighbours(self, row, column):
      minesCount = self.agentBoard[row][column]
      if(minesCount < 0):
          return 0
      (unrevealedList,safeCount,revealedMines) = self.get_knowledge(row, column)
      newInfo = 0;
      if(minesCount == revealedMines):
          for (r,c) in unrevealedList:
              self.agentBoard[r][c] = -3;
              newInfo = 1
      if(8-minesCount == safeCount):
          for (r,c) in unrevealedList:
              self.agentBoard[r][c] = -1;
              newInfo = 1
      return newInfo

In [0]:
env=Environment(5,10)
a=Agent(env)
blasts = 0
iterations = 0
while(iterations < 25):
  iterations += 1
  print(a.agentBoard)
  # x = int(random.uniform(0,a.dimension))
  # y = int(random.uniform(0,a.dimension))
  # while(a.agentBoard[x][y] != -2):
  #   x = int(random.uniform(0,a.dimension))
  #   y = int(random.uniform(0,a.dimension))
  # print (str(x)+"**"+str(y))
  x = int(input())
  y = int(input())
  result = a.env.reveal(x,y)
  if(result == -1):
    print("Bomb blast")
    blasts += 1
  a.agentBoard[x][y] = result
  a.updateKnowledge()
print("score : "+float(10-blasts)/10)


[[-2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]]
1
4
[[-2 -2 -2 -2 -2]
 [-2 -2 -2 -2  4]
 [-2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]]
2
0
[[-2 -2 -2 -2 -2]
 [-2 -2 -2 -2  4]
 [ 1 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]
 [-2 -2 -2 -2 -2]]
3
3
[[-2 -2 -2 -2 -2]
 [-2 -2 -2 -2  4]
 [ 1 -2 -2 -2 -2]
 [-2 -2 -2  3 -2]
 [-2 -2 -2 -2 -2]]
1
0
[[-2 -2 -2 -2 -2]
 [ 2 -2 -2 -2  4]
 [ 1 -2 -2 -2 -2]
 [-2 -2 -2  3 -2]
 [-2 -2 -2 -2 -2]]
4
0
[[-2 -2 -2 -2 -2]
 [ 2 -2 -2 -2  4]
 [ 1 -2 -2 -2 -2]
 [-2 -2 -2  3 -2]
 [ 1 -2 -2 -2 -2]]
1
2
[[-2 -2 -2 -2 -2]
 [ 2 -2  4 -2  4]
 [ 1 -2 -2 -2 -2]
 [-2 -2 -2  3 -2]
 [ 1 -2 -2 -2 -2]]
4
2
[[-2 -2 -2 -2 -2]
 [ 2 -2  4 -2  4]
 [ 1 -2 -2 -2 -2]
 [-2 -2 -2  3 -2]
 [ 1 -2  1 -2 -2]]
2
1
[[-2 -2 -2 -2 -2]
 [ 2 -2  4 -2  4]
 [ 1  2 -2 -2 -2]
 [-2 -2 -2  3 -2]
 [ 1 -2  1 -2 -2]]
4
1
[[-2 -2 -2 -2 -2]
 [ 2 -2  4 -2  4]
 [ 1  2 -2 -2 -2]
 [-2 -2 -2  3 -2]
 [ 1  2  1 -2 -2]]
3
1
[[-1 -1 -1 -2 -2]
 [ 2  3  4 -2  4]
 [ 1  2  2 -2 

KeyboardInterrupt: ignored